CREATE TABLE analysis_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    planning_document_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    model_name VARCHAR(255),
    prompt_version VARCHAR(100),
    requested_by BIGINT NOT NULL,
    requested_at TIMESTAMP NOT NULL,
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    failure_reason TEXT,
    token_usage BIGINT,
    raw_response TEXT,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_analysis_jobs_document FOREIGN KEY (planning_document_id) REFERENCES planning_documents (id),
    CONSTRAINT fk_analysis_jobs_requester FOREIGN KEY (requested_by) REFERENCES users (id),
    CONSTRAINT chk_analysis_jobs_status CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED'))
);
