CREATE TABLE requirements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_job_id BIGINT NOT NULL,
    external_requirement_id VARCHAR(100) NOT NULL,
    major_category VARCHAR(255) NOT NULL,
    middle_category VARCHAR(255) NOT NULL,
    minor_category VARCHAR(255) NOT NULL,
    title VARCHAR(500) NOT NULL,
    description TEXT NOT NULL,
    actor VARCHAR(255) NOT NULL,
    preconditions JSONB NOT NULL,
    requirement_trigger TEXT NOT NULL,
    expected_behaviors JSONB NOT NULL,
    constraints JSONB NOT NULL,
    evidences JSONB NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_requirements_analysis_job FOREIGN KEY (analysis_job_id) REFERENCES analysis_jobs (id),
    CONSTRAINT uq_requirements_job_external_id UNIQUE (analysis_job_id, external_requirement_id)
);
