CREATE TABLE outputs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    planning_document_id BIGINT NOT NULL,
    ambiguity_id BIGINT,
    output_type VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL,
    final_content TEXT,
    file_name VARCHAR(255),
    file_path VARCHAR(1000),
    external_service VARCHAR(20) NOT NULL,
    external_resource_id VARCHAR(255),
    external_url VARCHAR(1000),
    request_data JSONB,
    response_data JSONB,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    failure_reason VARCHAR(1000),
    CONSTRAINT fk_outputs_project FOREIGN KEY (project_id) REFERENCES projects (id),
    CONSTRAINT fk_outputs_document FOREIGN KEY (planning_document_id) REFERENCES planning_documents (id),
    CONSTRAINT fk_outputs_ambiguity FOREIGN KEY (ambiguity_id) REFERENCES ambiguities (id),
    CONSTRAINT fk_outputs_creator FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT chk_outputs_type CHECK (output_type IN ('CSV_EXPORT', 'MARKDOWN_EXPORT', 'JIRA_ISSUE')),
    CONSTRAINT chk_outputs_status CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED')),
    CONSTRAINT chk_outputs_external_service CHECK (external_service IN ('NONE', 'JIRA'))
);

CREATE TABLE lats_loop_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    output_id BIGINT NOT NULL,
    depth_step INTEGER NOT NULL,
    generated_draft TEXT NOT NULL,
    evaluation_score INTEGER NOT NULL,
    evaluation_feedback TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_lats_loop_logs_output FOREIGN KEY (output_id) REFERENCES outputs (id)
);
